### ISSUE TITLE
Parser Rewrite

### ISSUE THREAD

**Issue by Schmavery** [bsansouci/lisp-bot#7]
- [ ] Proper multi-line support
- [ ] Reader macros, examples: [CL](http://clhs.lisp.se/Body/f_set_ma.htm), [racket](http://docs.racket-lang.org/reference/Reader_Extension.html)
- [ ] Hashmap accessor sugar (I vote for map.key)

**Comment by bsansouci** [comment]
Just to build on this, the point of implementing something like the reader macro is two fold. First we get total creative freedom without losing speed of iteration, aka we can write whatever syntactic sugar we want and it'll just be function calls under the hood so we _can't_ break anything by removing some syntactic sugar. Second, this leaves us with a language that has two pivots and three moving parts: the syntax can change, the AST can change, the output JS can change. This is going to help us move much faster with the confidence that we won't break things, it'll also make it easier to unit test.

**Comment by bsansouci** [comment]
Redesigning the lexer we should think of a way to keep the format of the text in some AST-like data structure, allowing us to return the exact code that was written with details on what happened.

**Comment by bsansouci** [comment]
Just had a thought. When a reader macro generates an expression, it'll change what the pretty printer will return. Specifically everything will be function calls. 
For example:

``` clojure
user=> #{1 2 3}
(hash-set 1 2 3)
```

This _might_ be ok in this case, but if we also evaluate the returned expression we'll get something more like

``` clojure
user=> #{1 2 3}
(lambda (args ...) ( *complicated implementation ensues* ))
```

The problem that I see is that there are two transformations happening, `syntactic sugar -> expression` and `expression -> syntactic sugar`. Ideally we'd describe a two way mapping `syntactic sugar <=> expression`. Here's an example syntax that _might_ work:

``` clojure
(register-reader-macro #{&(expressions)} (hash-set &(expressions)))
```

I already see four problems with this:

1) I don't know if this kind of two way mapping will give us enough power to express all syntactic sugar for our language

2) Aren't we complecting things here? Maybe the transformation from syntactic sugar to expression should be separated from the other way around. I can see how we could end up with a very complicated system to allow all edge cases that happen in both `=>` and `<=`, all that in one "syntax".

3) This requires us to implement a DSL in our language that the lexer/parser can understand. This could either be inside the current one, bloating it to understand a different syntax, or be a totally different lexer/parser. The problem with the latter is we'd need to keep both ASTs in sync when updating them (and I can see us implementing native DS one day).

4) (this is the bigger problem) we're already reserving a token "&" as a way to distinguish between what are dumb tokens, and what are valid expressions that we want to bind data to. This leads to the ambiguity (in this case): do I want `&(expressions)` to collect all the expressions until the next token into a list? Ok then what does the `&(expressions)` on the other side mean? Does it just put the vector of tokens right there, or does it expand them into simple tokens with spaces in between (`(hash-set (1 2 3))` vs `(hash-set 1 2 3)`). We can't choose the latter because then the inverse transform isn't obvious anymore. We also can't do `#{&(expressions)} (hash-set &@(expressions))` to explicitly `unquote-splice` the `expressions` because then again the inverse transform isn't obvious. So we'd have to stick to `$(expressions)` a way to say "collect items into a vector" but depending on whether we're doing `=>` or `<=` it would take on different meanings. This is horrible because the difference is implicit and depends on _when_ that transformation is done, and that can lead to very very hard problems to debug. That said, I'm not 100% convinced it's bad, maybe it only leads to a certain category of problems that we can solve differently.

The pros for this syntax extension extender is that it's extremely readable, and can potentially lead to incredible syntactic sugar extensions.

Writing this down I realize that we could do this without compromise (all 4 problems). Here's a more pragmatic version of a "reader macro":

``` clojure
(define +hash-set-start-delimiter1+ "#")
(define +hash-set-start-delimiter2+ "{")
(define +hash-set-end-delimiter+ "}")
(define +token-delimiter+ " ")

(define hash-set-reader 
  (lambda (cur-char cur-state accumulator peek-next read-next already-reading)
    (cond (already-reading 
            (cond ((= cur-char +hash-set-end-delimiter+) `(hash-set ~@(reverse cur-state)))
                  ((= cur-char +token-delimiter+) (update! cur-state (lambda (state) (cons accumulator state))))
                  (true (update! accumulator (lambda (acc) (join acc cur-char))))))
          (true (and (= cur-char +hash-set-start-delimiter1+)
                     (= (peek-next) +hash-set-start-delimiter2+)
                     (do (read-next) true))))))

(register-reader-macro2 hash-set-reader)
```

There would be an internal little state machine that would have the input characters, a state for each one of the registered reader macros (cur-state and accumulator should be enough), and helpers: 
- `peek-next` just returns the next character (and moves the char pointer, so the next call to peek-next would be the next next character etc... This mutation would be local to this current lambda)
- `read-next` does like peek-next but moves for everyone the char pointer (and returns the character)
- `already-reading` tells the lambda it's already been called at least once and returned `true` in one of the previous calls

The lambda would either return:
- `()` if it returned true in the past, and is still running (aka it updated its `cur-state` or `accumulator`)
- `true/false` if it hasn't returned true in the past, meaning it hasn't started lexing the code (didn't match the start characters)
- valid ast, if it's done reading

The `do` at the end is to move the char pointer by one character (from "#" to "{") knowing that the internal state machine will also move it by one at the end of this lambda, and returning true at the end.

We then could implement the two way binding explained above using that little state-machine-handler.

This is just a made up proposal, there are many issues that we'd need to solve.

**Comment by Schmavery** [comment]
So I'll probably have to make you explain this to me in person because I'm dumb but I have some initial comments:
- What does curr-state look like?
- The accumulator is a ref?  Isn't that kind of gross?
- The lambda can't return either () or the ast, that is ambiguous in the case that is the ast is ().  Maybe we can return a tuple with a couple of relevant values including the accumulator and a bool.
- So I'm guessing that all reader macros get called every time you read a character (and you're not currently inside a reader macro).
- I'm not sure of the purpose of `already-reading`.
- I like the idea that we also define rules for the pretty printer, but I don't mind if those have to be defined separately.  There's no sense in overloading the syntax too heavily.

**Comment by bsansouci** [comment]
- **What does curr-state look like?** here it would be a list of expressions `(update! cur-state (lambda (state) (cons accumulator state)))` this appends `accumulator` onto that list (I forgot to clear the accumulator).
- **The accumulator is a ref? Isn't that kind of gross?** not just the `accumulator` but also the `cur-state`. I suspect it will be hard to keep this lambda pure, because of all the things it does. Also it's not so crazy because the function calling this one will represent a state machine, and mutations will occur all over the place anyways.
- **The lambda can't return either () or the ast, that is ambiguous in the case that is the ast is ().** Good call. Not sure what the best way to solve this is.
- **So I'm guessing that all reader macros get called every time you read a character (and you're not currently inside a reader macro).** Yes, and yes you can have nested reader macros (I think). It would still work. Say you have `#{1 2 #{1 2 3} 4}`, it would created a nested `cur-state` upon hitting the inner `hash-set`, parse it and return `(hash-set 1 2 3)` and go back to parsing the outer one. The `cur-state` would look like `(1 2 (hash-set 1 2 3))` at that point in time.
- **I'm not sure of the purpose of already-reading.** That's just a flag to tell the macro that it's been called at least once and is currently parsing. Maybe we can do without it.
- **I like the idea that we also define rules for the pretty printer, but I don't mind if those have to be defined separately. There's no sense in overloading the syntax too heavily.** The main problem with having those defined separately is that it's hard to keep those two definitions in sync. It'll also be hard to make sure that doing `SS=>expr=>SS=>expr2` leads to `expr == expr`. If we build something like what I described above (the syntactic sugar to write reader macros), maybe we can nail the balance between power and safety. If we don't, we'll most certainly give enough too much power (too many ways) to the user to write invalid reader macros.

**Comment by Schmavery** [comment]
Completely different paradigm that accomplishes the same goal: using regular expressions to rewrite the source text before parsing happens.
The idea is that you only manipulate strings, because you're just rewriting unparsed source.  It's like macros one level down.  We do one pass expanding using these (gotta make sure we don't have any recursive ones ;) ), then start the parsing phase (which doesn't have to be rewritten).

```
; Example of matching sets
(register-reader 
    "#{(.+)}" 
    (lambda (captured) 
        (join (list "(hash-set " (car captured) ")" ) "")
    )
)
```

EDIT: I'm an idiot this won't work.

**Comment by Schmavery** [comment]
Regardless of implementation, I'm inclined to think we should turn off this feature on the chatbot because you can potentially completely bork yourself over.  We could do this by simply manually doing (define register-reader "This operation cannot be performed.") in the bot-lib xD

**Comment by Schmavery** [comment]
I think we've agreed that we need a `read` function that calls the parser with a stream and separators defined in some way and returns a single parsed atom or sexp off of the top of the stream.  I'll start with the 2 main proposals for how the separators should work.

Let's use the hashset `#{1 2 3}` as an example.

**READ Function and Separators:**

Basically the separators should either be a regex or a list of terminating characters.  In this example, you'd be calling the `read` function on `1`, `2`, and `3`.  Basically you want to read until you hit a space or the `}` character. The regex will be more powerful and be able to account for extra spaces by using a regex like  " +|}".  However, I think this is the wrong solution because it makes it a little ambiguous as to where the cursor position should be after the read.

If we enter a list of terminating characters, it means we have to manually handle the cases where there are extra spaces etc, but on the other hand, it becomes very clear where the cursor will be after a `read`.  It will be on the character that terminated the read.  Then you can check the `curr-char` of the stream and check whether you are on a ' ' or a '}".  If you're on a space, you move the cursor forward until you're no longer on a space and then do another `read` if you don't hit a '}' first.

Just as a note, the terminating characters only matter if you're trying to match an identifier.

``` scheme
; First arg is the stream, second is the terminating characters.
(read "1 2 3" " ") ; returns (" 2 3" 1)
```

**Reader Macro:**

Reader macros are lambdas that receive an input stream, and return a tuple <bool,sexp> describing whether there was a match, and if so, the sexp that was generated.  If we choose not to implement a stream type, there are a number of ways of emulating the same behaviour: Either a string and a cursor int, or a string with peek and next functions come to mind.

At every character, every registered macro is called with the input stream starting at that point.  Each one returns their tuple, and the first longest match it chosen.  The parser then returns that sexp and jumps forward the number of characters read by the reader.  The parsing process restarts.  If no readers match, continue with the regular parsing procedure.

``` scheme
; We're trying to match #{1 2 3}

(define read-hashset-inner (lambda (str peek next) 
    (cond 
        ((= (peek str) "}") (list (next str) nil))
        ((= (peek str) " ") (list (next str) (read-hashset-inner (next str) peek next)))
        (true) 
            (let (res (read str " }")) 
                (list (car res) (cons (second res) (read-hashset-inner (car res) peek next)))))
; The returned strs might be a little messed up...
))

; peek: takes a string and returns the first character, 
;       accepts optional second argument for returning the nth character
; next: takes a string and pops the first character, 
;       returns the string with the cursor moved forward by one.
(register-reader hashset-reader (lambda (str peek next)
    (if (and (= (peek str) "#" ) (= (peek str 2) "{"))
        (true `(hash-set ~@(reverse (read-hashset-inner str peek next))))
        (str nil)
    )
)

; Bonus quote reader macro.
(register-reader quote (lambda (str) 
  (if (= (peek str) "'"))
    (let (res (read str " ")) (list (car res) `(quote ~@(second str))))
    (str nil)
))
```

**Comment by Schmavery** [comment]
``` scheme
; Bonus accessor macro.
(register-reader quote (lambda (str) 
  (let (res1 (read str " .") 
    (if (and (= (car (car res1)) ) ".") (type? (car res1) "function"))
      (let (res2 (cdr (car res1)) " ")
          (list (car res2) `(~@(car res1) ~@(car res2)))
      (list str nil))
))
```

EDIT: This recurses infinitely... We may not be done in our search for a solution...

**Comment by bsansouci** [comment]
After some offline discussion we've concluded that none of the systems proposed above give us enough power to express all of the different syntactic changes that we want. More specifically, it either can't allow nested hashsets, or it can't allow the dot operator (`obj.somefield.someotherfield`).

Therefore the solution that seems to make the most sense is to build a system with very powerful primitives, on top of which we could build any of the systems described above. We need to be able to define an arbitrary context free grammar with tokens (which hopefully can simply be regexes).

Here's what I propose:

``` scheme
(define dot-operator-internal
  (lambda ()
    '((start-token  dotted-ident             (lambda (v) v))
      (dotted-ident (ident DOT dotted-ident) (lambda (name fields) `(~name ~fields))
                    (ident)                  make-identifier-node)
      (ident        (regex /[a-z_0-9]*/i)    (lambda (v) v))
      (DOT          (regex /\./)             (lambda (v) nil)))))
```

This doesn't allow things like `({a: 10}.a)`. Here's an improved version.

``` scheme
(define dot-operator-internal
  (lambda (token-map)
    (let (expr-token (token-map expression)) 
      '((start-token         (expr-token DOT dotted-ident) (lambda (expr fields) `(~expr ~fields)))
        (dotted-ident        (expr-token DOT dotted-ident) (lambda (expr fields) `(~expr ~fields))
                             expr-token                    (lambda (v) v))
        (DOT                 (regex /\./)                  (lambda (v) nil))))))

(define-token (lambda (token-map)
    (let (new-token-map (assoc token-map dot-operator '(dot-operator-internal))) 
      (assoc new-token-map expression (cons dot-operator (new-token-map expression))))))
```

In this second version `token-map` is a map from identifiers to a list of tokens. Tokens are just functions that get the input-stream and the ast. You can look them up using their top level name (`assoc`ed inside `define-token`). This allows us to define small but reusable tokens, like `expression`. `define-token` simply calls the given `lambda` with the `token-map`, and has the power to do anything it wants with that. 
`token-map` contains a `start-token` which is the entry point of the CFG.

I'll spend some time implementing hashset with this and see how it goes.

**Comment by bsansouci** [comment]
Random early work on the hashset token

``` scheme

(define hash-set-token
  (lambda (token-map)
    (let (expr-token (token-map expression))
      '((start-token (HASH LBRACE expr-list RBRACE) make-into-hashset)
        (expr-list   (expr-token expr-list)         (lambda (token coll) (cons token coll))
                     (expr-token)                   (lambda (token)      (list token)))
        (HASH   (regex "#") ignore)
        (LBRACE (regex "{") ignore)
        (RBRACE (regex "}") ignore)))))

(define-token (lambda (token-map)
    (let (new-token-map (assoc token-map hash-set-token '(hash-set-token))) 
      (assoc new-token-map expression (cons hash-set-token (new-token-map expression))))))
```

**Comment by Schmavery** [comment]
Why is everything quoted?  Can't the token-map be a map from strings to lists of tokens?

I don't quite understand what a token is.  You said they are functions that get the stream and the ast, but you didn't say what they return.  Did you mean to say the get the stream and return the ast?

If I understand correctly, in these examples, you're creating a new token, adding it to the token-map with a corresponding function, and then adding its identifier to the list mapped to by the token name "expression".  This seems a little repetitive?

I'm not entirely sure how this structure can be read internally as a CFG.  You have a map of identifiers (or strings) to lists of functions.  How is this matched then?  All your rules are either a function or they're one element long (which would just be a call to a function later)?

**Comment by Schmavery** [comment]
Still can't believe we actually did this.
